navigation:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: Software & Data
    url: /software/
  - title: People
    url: /people/
  - title: Join Us

    url: /join/
